name: Trigger

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-24.04
    
    steps:
    - name: execute
      run: |
        gh workflow run process.yml --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOK }}
        
    - name: delay
      run: sleep 10800
      
    - name: next
      run: |
        gh workflow run trigger.yml --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOK }}
